#!/bin/sh

if [ ! -d _deploy ]
then
  git clone git@github.com:NaokiMizutani/NaokiMizutani.github.io _deploy
fi

rm -rf _deploy/*
cp -r _site/* _deploy/tech
cd _deploy
git add .
git add -u .
git commit -m "update"
git push
